image: rustlang/rust:nightly

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - test
  - release

clippy: 
  stage: test
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    - cargo clippy --version
  script:
    - cargo clippy -- -D warnings
  cache:
    key: clippy
    paths:
      - .cargo/
      - target/

fmt:
  stage: test
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add rustfmt
    - cargo fmt --version
  script:
    - cargo fmt --all -- --check

release:
  stage: release
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/school_paolo565_org 
  only:
    - v2
