image: node:10

test:
  before_script:
  - npm install
  script:
  - npm run lint
  except:
  - master

pages:
  before_script:
  - npm install
  script:
  - npm run prod
  artifacts:
    paths:
    - public
  only:
  - master
