[package]
name = "school_paolo565_org"
version = "2.0.0"
authors = ["Paolo Barbolini <paolo@paolo565.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
rocket = "0.4.2"
handlebars = "2.0.2"
rocket-include-handlebars = "0.12.4"
rocket-etag-if-none-match = "0.3.2"
md5 = "0.6.1"
rocket-include-static-resources = "0.9.2"
reqwest = "0.9.20"
unhtml = { version = "0.7.3", features = ["derive"] }
url = "2.1.0"
lazy_static = "1.4.0"
serde = "1.0.100"
serde_json = "1.0.40"
